# Generated by Django 3.2.9 on 2021-11-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211101_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
