# Generated by Django 3.2.9 on 2021-11-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pessoa_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='iden',
            field=models.IntegerField(null=True),
        ),
    ]
