# Generated by Django 3.2.9 on 2021-11-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pessoa_iden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='iden',
            field=models.IntegerField(null=True, verbose_name='id'),
        ),
    ]
