# Generated by Django 3.2.9 on 2021-11-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pessoa_iden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='iden',
            new_name='id_pessoa',
        ),
    ]
