# Generated by Django 3.2.9 on 2021-11-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pessoa_numero'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='PessoaTeste',
        ),
    ]
