# Generated by Django 3.2.9 on 2021-11-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20211101_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='estado',
            unique_together=set(),
        ),
    ]
