# Generated by Django 3.2.9 on 2021-11-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211101_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoateste',
            name='id_pessoa',
        ),
    ]
