# Generated by Django 3.2.9 on 2021-11-02 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_pessoateste_id_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='id_pessoa',
        ),
    ]
