# Generated by Django 3.2.9 on 2021-11-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_pessoa_id_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoateste',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
