# Generated by Django 3.2.9 on 2021-11-02 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_pessoateste_sobrenome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidade',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='bairro',
        ),
        migrations.DeleteModel(
            name='Bairro',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
