# Generated by Django 3.2.9 on 2021-11-02 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20211102_1919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PessoaTeste',
            new_name='Pessoa',
        ),
    ]
