# Generated by Django 3.2.9 on 2021-11-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_pessoa_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nascimento',
            field=models.CharField(max_length=100, null=True, verbose_name='data'),
        ),
    ]
